routes/web.php
<?php

use App\Http\Controllers\Admin\CompanyExportController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\DashBoardController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ProfileController;
use League\Glide\ServerFactory;
use Illuminate\Support\Facades\Request;
use App\Http\Controllers\Admin\MediaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//frontend
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

//backend
Route::group(['prefix' => 'admin','middleware' => ['admin']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('company-export', CompanyExportController::class);
    Route::get('/dashboard', [DashBoardController::class, 'index'])->name('dashboard');
    Route::get('profile',[ProfileController::class,'index'])->name('profile');
    Route::post('profile/{user}',[ProfileController::class,'update'])->name('profile.update');
    Route::get('glide/{path}', function($path){
        $server = ServerFactory::create([
            'source' => app('filesystem')->disk('media')->getDriver(),
            'cache' => storage_path('media'),
        ]);
        return $server->getImageResponse($path, Request::query());
    })->where('path', '.+');
    Route::get('/media', [MediaController::class, 'index'])->name('media');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Library\FlashMessages;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    use FlashMessages;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
//        Session::remove('message');
//        Session::remove('message_type');
//
//        $inputs = $request->all();
//        if(isset($inputs['message']) && isset($inputs['message_type'])){
//           Session::put('message',$inputs['message']);
//           Session::put('message_type',$inputs['message_type']);
//        }

        $roles = Role::orderBy('id','DESC')->paginate(5);

        return view('admin.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::get();
        return view('admin.roles.create',compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
            ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();

        return view('admin.roles.show',compact('role','rolePermissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();

        return view('admin.roles.edit',compact('role','permission','rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
            ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            DB::table("roles")->where('id', $id)->delete();
//        return redirect()->route('roles.index')
//            ->with('success','Role deleted successfully');
            self::success('Roles deleted successfully.');
            return response('Roles deleted successfully.', 200);
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="card">
                <div class="card-content">
                    @if (count($errors) > 0)
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger">
                                <button type="button" aria-hidden="true" class="close">
                                    <i class="material-icons">close</i>
                                </button>
                                <span>{{ $error }}</span>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 cols-sm-3 col-xs-12"></div>
            <div class="col-md-6 cols-sm-6 col-xs-12">
                {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">manage_accounts</i>
                        </div>
                        <h4 class="card-title">Create Role</h4>
                        <a class="btn btn-primary pull-right" href="{{ route('roles.index') }}">
                            <span class="btn-label">
                            <i class="material-icons">keyboard_arrow_left</i>
                            </span>
                            Back
                            <div class="ripple-container"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleName" class="bmd-label-floating">Name</label>
                            {!! Form::text('name', null, array('id' => 'exampleName','class' => 'form-control')) !!}
                        </div>
                        <div class="form-group">
                            <label for="exampleRole" class="bmd-label-floating">Permission</label>
                            @foreach($permission as $value)
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="form-check-input" name="permission[]" type="checkbox" value="{!! $value->id !!}" > {!! $value->name !!}
                                        <span class="form-check-sign">
                                                <span class="check"></span>
                                            </span>
                                    </label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="card-footer ">
                        <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
            <div class="col-md-3 cols-sm-3 col-xs-12"></div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card">
                    <div class="card-content">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    <button type="button" aria-hidden="true" class="close">
                                        <i class="material-icons">close</i>
                                    </button>
                                    <span>{{ $error }}</span>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 cols-sm-3 col-xs-12"></div>
                <div class="col-md-6 cols-sm-6 col-xs-12">
                    {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">manage_accounts</i>
                            </div>
                            <h4 class="card-title">Edit Role</h4>
                            <a class="btn btn-primary pull-right" href="{{ route('roles.index') }}">
                            <span class="btn-label">
                            <i class="material-icons">keyboard_arrow_left</i>
                            </span>
                                Back
                                <div class="ripple-container"></div>
                            </a>
                        </div>
                        <div class="card-body ">
                            <div class="form-group">
                                <label for="exampleName" class="bmd-label-floating">Name</label>
                                {!! Form::text('name', null, array('id' => 'exampleName','class' => 'form-control')) !!}
                            </div>
                            <div class="form-group">
                                <label for="exampleRole" class="bmd-label-floating">Permission</label>
                                @foreach($permission as $value)
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" name="permission[]" type="checkbox" value="{!! $value->id !!}" @php echo in_array($value->id, $rolePermissions) ? 'checked': ''; @endphp> {!! $value->name !!}
                                            <span class="form-check-sign">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="card-footer ">
                            <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                <div class="col-md-3 cols-sm-3 col-xs-12"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="content">
        <div class="container-fluid">
            @include('layouts.message')
            <div class="row">
                <div class="card">
                    <div class="card-content">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    <button type="button" aria-hidden="true" class="close">
                                        <i class="material-icons">close</i>
                                    </button>
                                    <span>{{ $error }}</span>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">manage_accounts</i>
                            </div>
                            <h4 class="card-title">Role Management</h4>
                            <div class="pull-right">
                                @can('role-create')
                                    <a class="btn btn-success" href="{{ route('roles.create') }}"> Create New Role </a>
                                @endcan
                            </div>
                        </div>
                        <div class="card-body">


                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        <th>Name</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($roles as $key => $role)
                                        <tr>
                                            <td class="text-center">{{ ++$i }}</td>
                                            <td>{{ $role->name }}</td>
                                            <td class="td-actions text-right">
                                                <button type="button" rel="tooltip" class="btn btn-info" onclick="window.location.href = '{{ route('roles.show',$role->id) }}'">
                                                    <i class="material-icons">visibility</i>
                                                </button>
                                                @can('role-edit')
                                                <button type="button" rel="tooltip" class="btn btn-success" onclick="window.location.href = '{{ route('roles.edit',$role->id) }}'">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                @endcan
                                                <form method="post" class="delete-form"  style="display:inline" data-route="{{route('roles.destroy',$role->id)}}">
                                                    @method('delete')
                                                <button type="submit" rel="tooltip" class="btn btn-danger" >
                                                    <i class="material-icons">close</i>
                                                </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('page_scripts')
    <script type="text/javascript">
        $(document).ready(function() {

            $('.delete-form').on('submit', function(e) {
                e.preventDefault();
                var button = $(this);

                Swal.fire({
                    icon: 'warning',
                    title: 'Are you sure you want to delete this record?',
                    showDenyButton: false,
                    showCancelButton: true,
                    confirmButtonText: 'Yes'
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if(result.value){
                        $.ajax({
                            type: 'delete',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            url:  button.data('route'),
                            data: {
                                '_method': 'delete'
                            },
                            success: function (response, textStatus, xhr) {
                                Swal.fire({
                                    icon: 'success',
                                    title: response,
                                    showDenyButton: false,
                                    showCancelButton: false,
                                    confirmButtonText: 'Yes'
                                }).then((result) => {
                                    window.location='{{ route('roles.index',['success'=>'Roles deleted successfully.']) }}'
                                });
                            }
                        });
                    }else{
                        if(result.dismiss === "cancel"){

                        }
                    }
                });

            })
        });
    </script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <a class="btn btn-primary pull-right" href="{{ route('roles.index') }}">
                                <span class="btn-label">
                                    <i class="material-icons">manage_accounts</i>
                                </span>
                                Back <div class="ripple-container"></div>
                            </a>
                        </div>
                        <div class="card-body ">
                            <div class="form-group">
                                <label for="exampleEmail" class="bmd-label-floating"> Name</label>
                                <input type="email" class="form-control" id="exampleEmail" required="true" value="{{ $role->name }}" disabled>
                            </div>
                            <div class="form-group">
                                <label for="examplePassword1" class="bmd-label-floating"> Roles</label>
                                @if(!empty($rolePermissions))
                                    @foreach($rolePermissions as $v)
                                        <label class="label label-success">{{ $v->name }},</label>
                                    @endforeach
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection