routes/web.php
<?php

use App\Http\Controllers\Admin\CompanyExportController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\DashBoardController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ProfileController;
use League\Glide\ServerFactory;
use Illuminate\Support\Facades\Request;
use App\Http\Controllers\Admin\MediaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//frontend
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

//backend
Route::group(['prefix' => 'admin','middleware' => ['admin']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('company-export', CompanyExportController::class);
    Route::get('/dashboard', [DashBoardController::class, 'index'])->name('dashboard');
    Route::get('profile',[ProfileController::class,'index'])->name('profile');
    Route::post('profile/{user}',[ProfileController::class,'update'])->name('profile.update');
    Route::get('glide/{path}', function($path){
        $server = ServerFactory::create([
            'source' => app('filesystem')->disk('media')->getDriver(),
            'cache' => storage_path('media'),
        ]);
        return $server->getImageResponse($path, Request::query());
    })->where('path', '.+');
    Route::get('/media', [MediaController::class, 'index'])->name('media');
});

app/Models/CompanyExport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Permission\Traits\HasRoles;

class CompanyExport extends Model implements HasMedia
{
    use HasFactory, Notifiable, HasRoles, InteractsWithMedia;

    protected $fillable = ['name','address','telephone'];
    protected $table = 'company_export';

    /**
     * @return \Spatie\MediaLibrary\MediaCollections\Models\Media|null
     */

    public function getLogoAttribute(){
        return $this->getFirstMedia('logo');
    }


}

app/Http/Controllers/Admin/CompanyExportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Library\FlashMessages;
use App\Models\CompanyExport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CompanyExportController extends AdminBaseController
{
    use FlashMessages;
    protected $diskName = 'company-export';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:company-export-list|company-export-create|company-export-edit|company-export-delete', ['only' => ['index','store']]);
        $this->middleware('permission:company-export-create', ['only' => ['create','store']]);
        $this->middleware('permission:company-export-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:company-export-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $companyExportList = CompanyExport::orderBy('id','DESC')->paginate(5);

        return view('admin.company_export.index',compact('companyExportList'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.company_export.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $lastRecord = CompanyExport::query()
            ->where('code','like','CE%')
            ->orderBy('code','desc')
            ->first();

        $companyExport = CompanyExport::create($request->all());
        $code = $lastRecord ? (int)str_replace("CE","",$lastRecord->code) : 0;
        $companyExport->code = is_null($lastRecord) ? 'CE0001' : 'CE'.sprintf('%04d', $code + 1);

        if($request->hasFile('logo') && $request->file('logo')->isValid()){
            $companyExport->addMediaFromRequest('logo')
                ->toMediaCollection('logo',$this->diskName);
        }

        $companyExport->save();

        return redirect()->route('company-export.index')
            ->with('success','Company export created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = CompanyExport::find($id);
        return view('admin.company_export.show',compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = CompanyExport::find($id);
        return view('admin.company_export.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $company = CompanyExport::find($id);
        $company->fill($request->all());

        if($request->hasFile('logo') && $request->file('logo')->isValid()){
//            $company->deletePreservingMedia('logo');
//            $company->save();
            $company->clearMediaCollection('logo');
            $company->addMediaFromRequest('logo')
                ->toMediaCollection('logo',$this->diskName);
        }

        $company->save();

        return redirect()->route('company-export.index')
            ->with('success','Company export updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("company_export")->where('id', $id)->delete();
        self::success('Company export deleted successfully.');
        return response('Company export deleted successfully.', 200);
    }
}

resources/views/admin/company_export/create.blade.php
@extends('layouts.app')
@push('page-link') <a class="navbar-brand" href="{{ route('company-export.index') }}">Company Export</a> @endpush
@section('content')
<div class="content">
    <div class="container-fluid">
        @if (count($errors) > 0)
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    <a type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <i class="material-icons">close</i>
                    </a>
                    <span>{{ trans('error.count',['attribute'=>count($errors)]) }}</span>
                </div>
            </div>
        </div>
        @endif
        <div class="row">
            <div class="col-md-3 cols-sm-3 col-xs-12"></div>
            <div class="col-md-6 cols-sm-6 col-xs-12">
                {!! Form::open(['method' => 'POST','route' => 'company-export.store','enctype'=>'multipart/form-data']) !!}
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <a class="btn btn-primary" href="{{ route('company-export.index') }}">
                            <span class="btn-label">
                            <i class="material-icons">keyboard_arrow_left</i>
                            </span>
                            Back
                            <div class="ripple-container"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name" class="bmd-label-floating">Name</label>
                            {!! Form::text('name', null, array('id' => 'name','class' => 'form-control')) !!}
                            @error('name')
                            <label id="name-error" class="error" for="name">{{ $message }}</label>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="address" class="bmd-label-floating">Address</label>
                            {!! Form::text('address', null, array('id' => 'address','class' => 'form-control')) !!}
                            @error('address')
                            <label id="name-address" class="error" for="address">{{ $message }}</label>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="telephone" class="bmd-label-floating">Telephone</label>
                            {!! Form::text('telephone', null, array('id' => 'telephone','class' => 'form-control')) !!}
                            @error('telephone')
                            <label id="name-telephone" class="error" for="telephone">{{ $message }}</label>
                            @enderror
                        </div>
                        <div class="form-group">
                            <h4 class="title">Logo</h4>
                            <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                <div class="fileinput-new thumbnail">
                                    <img src="{{ asset('material-dashboard-pro/assets/img/image_placeholder.jpg') }}" alt="...">
                                </div>
                                <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                <div>
                                  <span class="btn btn-rose btn-round btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists">Change</span>
                                      {!! Form::file('logo', null, array('id' => 'logo')) !!}
                                  </span>
                                    <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer ">
                        <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
            <div class="col-md-3 cols-sm-3 col-xs-12"></div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/company_export/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card">
                    <div class="card-content">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    <button type="button" aria-hidden="true" class="close">
                                        <i class="material-icons">close</i>
                                    </button>
                                    <span>{{ $error }}</span>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 cols-sm-3 col-xs-12"></div>
                <div class="col-md-6 cols-sm-6 col-xs-12">
                    {!! Form::model($company, ['method' => 'PATCH','route' => ['company-export.update', $company->id],'enctype'=>'multipart/form-data']) !!}
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <a class="btn btn-primary" href="{{ route('company-export.index') }}">
                            <span class="btn-label">
                            <i class="material-icons">keyboard_arrow_left</i>
                            </span>
                                Back
                                <div class="ripple-container"></div>
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name" class="bmd-label-floating">Name</label>
                                {!! Form::text('name', null, array('id' => 'name','class' => 'form-control')) !!}
                                @error('name')
                                <label id="name-error" class="error" for="name">{{ $message }}</label>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="address" class="bmd-label-floating">Address</label>
                                {!! Form::text('address', null, array('id' => 'address','class' => 'form-control')) !!}
                                @error('address')
                                <label id="name-address" class="error" for="address">{{ $message }}</label>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="telephone" class="bmd-label-floating">Telephone</label>
                                {!! Form::text('telephone', null, array('id' => 'telephone','class' => 'form-control')) !!}
                                @error('telephone')
                                <label id="name-telephone" class="error" for="telephone">{{ $message }}</label>
                                @enderror
                            </div>
                            <div class="form-group">
                                <h4 class="title">Logo</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        @if($company->logo)
                                            <img src="{{ $company->logo->getFullUrl() }}" alt="{{ $company->logo->getCustomProperty('alt') }}">
                                        @else
                                            <img src="{{ asset('material-dashboard-pro/assets/img/image_placeholder.jpg') }}" alt="...">
                                        @endif
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                  <span class="btn btn-rose btn-round btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists">Change</span>
                                      {!! Form::file('logo', null, array('id' => 'logo')) !!}
                                  </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                    </div>
                </div>
                <div class="col-md-3 cols-sm-3 col-xs-12"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/company_export/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content">
        <div class="container-fluid">
            @include('layouts.message')
            <div class="row">
                <div class="card">
                    <div class="card-content">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    <button type="button" aria-hidden="true" class="close">
                                        <i class="material-icons">close</i>
                                    </button>
                                    <span>{{ $error }}</span>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">manage_accounts</i>
                            </div>
                            <h4 class="card-title">Company Export Management</h4>
                            <div class="pull-right">
                                @can('company-export-create')
                                    <a class="btn btn-success" href="{{ route('company-export.create') }}"> Create New Company Export </a>
                                @endcan
                            </div>
                        </div>
                        <div class="card-body">


                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        <th>Name</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($companyExportList as $key => $company)
                                        <tr>
                                            <td class="text-center">{{ ++$i }}</td>
                                            <td>{{ $company->name }}</td>
                                            <td class="td-actions text-right">
                                                <button type="button" rel="tooltip" class="btn btn-info" onclick="window.location.href = '{{ route('company-export.show',$company->id) }}'">
                                                    <i class="material-icons">visibility</i>
                                                </button>
                                                @can('company-export-edit')
                                                <button type="button" rel="tooltip" class="btn btn-success" onclick="window.location.href = '{{ route('company-export.edit',$company->id) }}'">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                @endcan
                                                <form method="post" class="delete-form"  style="display:inline" data-route="{{route('company-export.destroy',$company->id)}}">
                                                    @method('delete')
                                                <button type="submit" rel="tooltip" class="btn btn-danger" >
                                                    <i class="material-icons">close</i>
                                                </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('page_scripts')
    <script type="text/javascript">
        $(document).ready(function() {

            $('.delete-form').on('submit', function(e) {
                e.preventDefault();
                var button = $(this);

                Swal.fire({
                    icon: 'warning',
                    title: 'Are you sure you want to delete this record?',
                    showDenyButton: false,
                    showCancelButton: true,
                    confirmButtonText: 'Yes'
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if(result.value){
                        $.ajax({
                            type: 'delete',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            url:  button.data('route'),
                            data: {
                                '_method': 'delete'
                            },
                            success: function (response, textStatus, xhr) {
                                Swal.fire({
                                    icon: 'success',
                                    title: response,
                                    showDenyButton: false,
                                    showCancelButton: false,
                                    confirmButtonText: 'Yes'
                                }).then((result) => {
                                    window.location='{{ route('company-export.index',['success'=>'Company export deleted successfully.']) }}'
                                });
                            }
                        });
                    }else{
                        if(result.dismiss === "cancel"){

                        }
                    }
                });

            })
        });
    </script>
@endpush

resources/views/admin/company_export/show.blade.php
@extends('layouts.app')
@push('page-link') <a class="navbar-brand" href="{{ route('company-export.index') }}">Company Export</a> @endpush
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <a class="btn btn-primary" href="{{ route('company-export.index') }}">
                            <span class="btn-label">
                            <i class="material-icons">keyboard_arrow_left</i>
                            </span>
                                Back
                                <div class="ripple-container"></div>
                            </a>
                        </div>
                        <div class="card-body ">
                            <div class="form-group">
                                <label for="name" class="bmd-label-floating"> Name</label>
                                <input type="text" class="form-control" id="name" required="true" value="{{ $company->name }}" disabled>
                            </div>
                            <div class="form-group">
                                <label for="code" class="bmd-label-floating"> Code</label>
                                <input type="text" class="form-control" id="code" required="true" value="{{ $company->code }}" disabled>
                            </div>
                            <div class="form-group">
                                <label for="address" class="bmd-label-floating"> Address</label>
                                <input type="text" class="form-control" id="address" required="true" value="{{ $company->address }}" disabled>
                            </div>
                            <div class="form-group">
                                <label for="telephone" class="bmd-label-floating"> Telephone</label>
                                <input type="text" class="form-control" id="telephone" required="true" value="{{ $company->telephone }}" disabled>
                            </div>

                            <div class="form-group">
                                <h4 class="title">Logo</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{ $company->logo->getFullUrl() }}" alt="{{ $company->logo->getCustomProperty('alt') }}">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection